// GENERATED from docs/protocol/*.tsv by tools/gen-effects.py — do not edit by hand.
import type { Effect } from './types.ts'

export const melk: Effect[] = [
  {"id": 0, "group": "Basic", "name": "Auto Play"},
  {"id": 1, "group": "Basic", "name": "Magic Forward"},
  {"id": 2, "group": "Basic", "name": "Magic Back"},
  {"id": 212, "group": "Basic", "name": "7-Color Energy"},
  {"id": 193, "group": "Basic", "name": "7-Color Jump"},
  {"id": 194, "group": "Basic", "name": "R-G-B Jump"},
  {"id": 195, "group": "Basic", "name": "Y-C-P Jump"},
  {"id": 196, "group": "Basic", "name": "7-Color Strobe"},
  {"id": 197, "group": "Basic", "name": "R-G-B Strobe"},
  {"id": 198, "group": "Basic", "name": "Y-C-P Strobe"},
  {"id": 199, "group": "Basic", "name": "7-Color Gradual"},
  {"id": 200, "group": "Basic", "name": "R-Y Gradual"},
  {"id": 201, "group": "Basic", "name": "R-P Gradual"},
  {"id": 202, "group": "Basic", "name": "G-C Gradual"},
  {"id": 203, "group": "Basic", "name": "G-Y Gradual"},
  {"id": 204, "group": "Basic", "name": "B-P Gradual"},
  {"id": 205, "group": "Basic", "name": "Red Marquee"},
  {"id": 206, "group": "Basic", "name": "Green Marquee"},
  {"id": 207, "group": "Basic", "name": "Blue Marquee"},
  {"id": 208, "group": "Basic", "name": "Yellow Marquee"},
  {"id": 209, "group": "Basic", "name": "Cyan Marquee"},
  {"id": 210, "group": "Basic", "name": "Purple Marquee"},
  {"id": 211, "group": "Basic", "name": "White Marquee"},
  {"id": 77, "group": "Basic", "name": "7-Color Race"},
  {"id": 78, "group": "Basic", "name": "7-Color Race Back"},
  {"id": 79, "group": "Basic", "name": "R-G-B Race"},
  {"id": 80, "group": "Basic", "name": "R-G-B Race Back"},
  {"id": 81, "group": "Basic", "name": "Y-C-P Race"},
  {"id": 82, "group": "Basic", "name": "Y-C-P Race Back"},
  {"id": 83, "group": "Basic", "name": "7-Color Wave"},
  {"id": 84, "group": "Basic", "name": "7-Color Wave Back"},
  {"id": 85, "group": "Basic", "name": "R-G-B Wave"},
  {"id": 86, "group": "Basic", "name": "R-G-B Wave Back"},
  {"id": 87, "group": "Basic", "name": "Y-C-P Wave"},
  {"id": 88, "group": "Basic", "name": "Y-C-P Wave Back"},
  {"id": 181, "group": "Basic", "name": "7-Color Flush"},
  {"id": 182, "group": "Basic", "name": "7-Color Flush Back"},
  {"id": 183, "group": "Basic", "name": "R-G-B Flush"},
  {"id": 184, "group": "Basic", "name": "R-G-B Flush Back"},
  {"id": 185, "group": "Basic", "name": "Y-C-P Flush"},
  {"id": 186, "group": "Basic", "name": "Y-C-P Flush Back"},
  {"id": 187, "group": "Basic", "name": "7-Color Flush Close"},
  {"id": 188, "group": "Basic", "name": "7-Color Flush Open"},
  {"id": 189, "group": "Basic", "name": "R-G-B Flush Close"},
  {"id": 190, "group": "Basic", "name": "R-G-B Flush Open"},
  {"id": 191, "group": "Basic", "name": "Y-C-P Flush Close"},
  {"id": 192, "group": "Basic", "name": "Y-C-P Flush Open"},
  {"id": 57, "group": "Curtain", "name": "7-Color Close"},
  {"id": 58, "group": "Curtain", "name": "7-Color Open"},
  {"id": 59, "group": "Curtain", "name": "R-G-B Close"},
  {"id": 60, "group": "Curtain", "name": "R-G-B Open"},
  {"id": 61, "group": "Curtain", "name": "Y-C-P Close"},
  {"id": 62, "group": "Curtain", "name": "Y-C-P Open"},
  {"id": 63, "group": "Curtain", "name": "Red Close"},
  {"id": 64, "group": "Curtain", "name": "Red Open"},
  {"id": 65, "group": "Curtain", "name": "Green Close"},
  {"id": 66, "group": "Curtain", "name": "Green Open"},
  {"id": 67, "group": "Curtain", "name": "Blue Close"},
  {"id": 68, "group": "Curtain", "name": "Blue Open"},
  {"id": 69, "group": "Curtain", "name": "Yellow Close"},
  {"id": 70, "group": "Curtain", "name": "Yellow Open"},
  {"id": 71, "group": "Curtain", "name": "Cyan Close"},
  {"id": 72, "group": "Curtain", "name": "Cyan Open"},
  {"id": 73, "group": "Curtain", "name": "Purple Close"},
  {"id": 74, "group": "Curtain", "name": "Purple Open"},
  {"id": 75, "group": "Curtain", "name": "White Close"},
  {"id": 76, "group": "Curtain", "name": "White Open"},
  {"id": 3, "group": "Trans", "name": "7-Color Trans"},
  {"id": 4, "group": "Trans", "name": "7-Color Trans Back"},
  {"id": 5, "group": "Trans", "name": "R-G-B Trans"},
  {"id": 6, "group": "Trans", "name": "R-G-B Trans Back"},
  {"id": 7, "group": "Trans", "name": "Y-C-P Trans"},
  {"id": 8, "group": "Trans", "name": "Y-C-P Trans Back"},
  {"id": 9, "group": "Trans", "name": "6-Color to Red"},
  {"id": 10, "group": "Trans", "name": "6-Color to Red Back"},
  {"id": 11, "group": "Trans", "name": "6-Color to Green"},
  {"id": 12, "group": "Trans", "name": "6-Color to Green Back"},
  {"id": 13, "group": "Trans", "name": "6-Color to Blue"},
  {"id": 14, "group": "Trans", "name": "6-Color to Blue Back"},
  {"id": 15, "group": "Trans", "name": "6-Color to Cyan"},
  {"id": 16, "group": "Trans", "name": "6-Color to Cyan Back"},
  {"id": 17, "group": "Trans", "name": "6-Color to Yellow"},
  {"id": 18, "group": "Trans", "name": "6-Color to Yellow Back"},
  {"id": 19, "group": "Trans", "name": "6-Color to Purple"},
  {"id": 20, "group": "Trans", "name": "6-Color to Purple Back"},
  {"id": 21, "group": "Trans", "name": "6-Color to White"},
  {"id": 22, "group": "Trans", "name": "6-Color to White Back"},
  {"id": 39, "group": "Water", "name": "7-Color Water"},
  {"id": 40, "group": "Water", "name": "7-Color Water Back"},
  {"id": 41, "group": "Water", "name": "R-G-B Water"},
  {"id": 42, "group": "Water", "name": "R-G-B Water Back"},
  {"id": 43, "group": "Water", "name": "Y-C-P Water"},
  {"id": 44, "group": "Water", "name": "Y-C-P Water Back"},
  {"id": 45, "group": "Water", "name": "R-G Water"},
  {"id": 46, "group": "Water", "name": "R-G Water Back"},
  {"id": 47, "group": "Water", "name": "G-B Water"},
  {"id": 48, "group": "Water", "name": "G-B Water Back"},
  {"id": 49, "group": "Water", "name": "Y-B Water"},
  {"id": 50, "group": "Water", "name": "Y-B Water Back"},
  {"id": 51, "group": "Water", "name": "Y-C Water"},
  {"id": 52, "group": "Water", "name": "Y-C Water Back"},
  {"id": 53, "group": "Water", "name": "C-P Water"},
  {"id": 54, "group": "Water", "name": "C-P Water Back"},
  {"id": 55, "group": "Water", "name": "White Water"},
  {"id": 56, "group": "Water", "name": "White Water Back"},
  {"id": 143, "group": "Flow", "name": "W-R-W Flow"},
  {"id": 144, "group": "Flow", "name": "W-R-W Flow Back"},
  {"id": 145, "group": "Flow", "name": "W-G-W Flow"},
  {"id": 146, "group": "Flow", "name": "W-G-W Flow Back"},
  {"id": 147, "group": "Flow", "name": "W-B-W Flow"},
  {"id": 148, "group": "Flow", "name": "W-B-W Flow Back"},
  {"id": 149, "group": "Flow", "name": "W-Y-W Flow"},
  {"id": 150, "group": "Flow", "name": "W-Y-W Flow Back"},
  {"id": 151, "group": "Flow", "name": "W-C-W Flow"},
  {"id": 152, "group": "Flow", "name": "W-C-W Flow Back"},
  {"id": 153, "group": "Flow", "name": "W-P-W Flow"},
  {"id": 154, "group": "Flow", "name": "W-P-W Flow Back"},
  {"id": 155, "group": "Flow", "name": "R-W-R Flow"},
  {"id": 156, "group": "Flow", "name": "R-W-R Flow Back"},
  {"id": 157, "group": "Flow", "name": "G-W-G Flow"},
  {"id": 158, "group": "Flow", "name": "G-W-G Flow Back"},
  {"id": 159, "group": "Flow", "name": "B-W-B Flow"},
  {"id": 160, "group": "Flow", "name": "B-W-B Flow Back"},
  {"id": 161, "group": "Flow", "name": "Y-W-Y Flow"},
  {"id": 162, "group": "Flow", "name": "Y-W-Y Flow Back"},
  {"id": 163, "group": "Flow", "name": "C-W-C Flow"},
  {"id": 164, "group": "Flow", "name": "C-W-C Flow Back"},
  {"id": 165, "group": "Flow", "name": "P-W-P Flow"},
  {"id": 166, "group": "Flow", "name": "P-W-P Flow Back"},
  {"id": 23, "group": "Tail", "name": "7-Color Tail"},
  {"id": 24, "group": "Tail", "name": "7-Color Tail Back"},
  {"id": 25, "group": "Tail", "name": "Red Tail"},
  {"id": 26, "group": "Tail", "name": "Red Tail Back"},
  {"id": 27, "group": "Tail", "name": "Green Tail"},
  {"id": 28, "group": "Tail", "name": "Green Tail Back"},
  {"id": 29, "group": "Tail", "name": "Blue Tail"},
  {"id": 30, "group": "Tail", "name": "Blue Tail Back"},
  {"id": 31, "group": "Tail", "name": "Yellow Tail"},
  {"id": 32, "group": "Tail", "name": "Yellow Tail Back"},
  {"id": 33, "group": "Tail", "name": "Cyan Tail"},
  {"id": 34, "group": "Tail", "name": "Cyan Tail Back"},
  {"id": 35, "group": "Tail", "name": "Purple Tail"},
  {"id": 36, "group": "Tail", "name": "Purple Tail Back"},
  {"id": 37, "group": "Tail", "name": "White Tail"},
  {"id": 38, "group": "Tail", "name": "White Tail Back"},
  {"id": 89, "group": "Run", "name": "Red Running"},
  {"id": 91, "group": "Run", "name": "Green Running"},
  {"id": 93, "group": "Run", "name": "Blue Running"},
  {"id": 95, "group": "Run", "name": "Yellow Running"},
  {"id": 97, "group": "Run", "name": "Cyan Running"},
  {"id": 99, "group": "Run", "name": "Purple Running"},
  {"id": 101, "group": "Run", "name": "White Running"},
  {"id": 103, "group": "Run", "name": "7-Color Running"},
  {"id": 105, "group": "Run", "name": "R-G-B Running"},
  {"id": 107, "group": "Run", "name": "Y-C-P Running"},
  {"id": 109, "group": "Run", "name": "B-P-C-Y Running"},
  {"id": 111, "group": "Run", "name": "B-G-C-Y Running"},
  {"id": 113, "group": "Run", "name": "Red-Dot in White Running"},
  {"id": 115, "group": "Run", "name": "Green-Dot in Red Running"},
  {"id": 117, "group": "Run", "name": "Blue-Dot in Green Running"},
  {"id": 119, "group": "Run", "name": "Yellow-Dot in Blue Running"},
  {"id": 121, "group": "Run", "name": "Cyan-Dot in Yellow Running"},
  {"id": 123, "group": "Run", "name": "Purple-Dot in Cyan Running"},
  {"id": 125, "group": "Run", "name": "White-Dot in Purple Running"},
  {"id": 127, "group": "Run", "name": "White-Dot in Red Running"},
  {"id": 129, "group": "Run", "name": "7-Color in Red Running"},
  {"id": 131, "group": "Run", "name": "7-Color in Green Running"},
  {"id": 133, "group": "Run", "name": "7-Color in Blue Running"},
  {"id": 135, "group": "Run", "name": "7-Color in Yellow Running"},
  {"id": 137, "group": "Run", "name": "7-Color in Cyan Running"},
  {"id": 139, "group": "Run", "name": "7-Color in Purple Running"},
  {"id": 141, "group": "Run", "name": "7-Color in White Running"},
  {"id": 167, "group": "Run", "name": "Green-Dot in Blue Running"},
  {"id": 169, "group": "Run", "name": "Green-Dot in Red Running"},
  {"id": 171, "group": "Run", "name": "Red-Dot in Blue Running"},
  {"id": 173, "group": "Run", "name": "Cyan-Dot in Yellow Running"},
  {"id": 175, "group": "Run", "name": "Yellow-Dot in Purple Running"},
  {"id": 177, "group": "Run", "name": "White-Dot in Yelllow Running"},
  {"id": 179, "group": "Run", "name": "Yellow-Dot in White Running"},
  {"id": 90, "group": "RunBack", "name": "Red Run Back"},
  {"id": 92, "group": "RunBack", "name": "Green Run Back"},
  {"id": 94, "group": "RunBack", "name": "Blue Run Back"},
  {"id": 96, "group": "RunBack", "name": "Yellow Run Back"},
  {"id": 98, "group": "RunBack", "name": "Cyan Run Back"},
  {"id": 100, "group": "RunBack", "name": "Purple Run Back"},
  {"id": 102, "group": "RunBack", "name": "White Run Back"},
  {"id": 104, "group": "RunBack", "name": "7-Color Run Back"},
  {"id": 106, "group": "RunBack", "name": "R-G-B Run Back"},
  {"id": 108, "group": "RunBack", "name": "Y-C-P Run Back"},
  {"id": 110, "group": "RunBack", "name": "B-P-C-Y Run Back"},
  {"id": 112, "group": "RunBack", "name": "B-G-C-Y Run Back"},
  {"id": 114, "group": "RunBack", "name": "Red-Dot in White Run Back"},
  {"id": 116, "group": "RunBack", "name": "Green-Dot in Red Run Back"},
  {"id": 118, "group": "RunBack", "name": "Blue-Dot in Green Run Back"},
  {"id": 120, "group": "RunBack", "name": "Yellow-Dot in Blue Run Back"},
  {"id": 122, "group": "RunBack", "name": "Cyan-Dot in Yellow Run Back"},
  {"id": 124, "group": "RunBack", "name": "Purple-Dot in Cyan Run Back"},
  {"id": 126, "group": "RunBack", "name": "White-Dot in Purple Run Back"},
  {"id": 128, "group": "RunBack", "name": "White-Dot in Red Run Back"},
  {"id": 130, "group": "RunBack", "name": "7-Color in Red Run Back"},
  {"id": 132, "group": "RunBack", "name": "7-Color in Green Run Back"},
  {"id": 134, "group": "RunBack", "name": "7-Color in Blue Run Back"},
  {"id": 136, "group": "RunBack", "name": "7-Color in Yellow Run Back"},
  {"id": 138, "group": "RunBack", "name": "7-Color in Cyan Run Back"},
  {"id": 140, "group": "RunBack", "name": "7-Color in Purple Run Back"},
  {"id": 142, "group": "RunBack", "name": "7-Color in White Run Back"},
  {"id": 168, "group": "RunBack", "name": "Green-Dot in Blue Run Back"},
  {"id": 170, "group": "RunBack", "name": "Green-Dot in Red Run Back"},
  {"id": 172, "group": "RunBack", "name": "Red-Dot in Blue Run Back"},
  {"id": 174, "group": "RunBack", "name": "Cyan-Dot in Yellow Run Back"},
  {"id": 176, "group": "RunBack", "name": "Yellow-Dot in Purple Run Back"},
  {"id": 178, "group": "RunBack", "name": "White-Dot in Yelllow Run Back"},
  {"id": 180, "group": "RunBack", "name": "Yellow-Dot in White Run Back"},
  {"id": 1, "group": "Scenes", "name": "Sunrise"},
  {"id": 2, "group": "Scenes", "name": "Sunset"},
  {"id": 3, "group": "Scenes", "name": "Birthday"},
  {"id": 4, "group": "Scenes", "name": "Candlelight"},
  {"id": 5, "group": "Scenes", "name": "Fireworks"},
  {"id": 6, "group": "Scenes", "name": "Party"},
  {"id": 7, "group": "Scenes", "name": "Datiny"},
  {"id": 8, "group": "Scenes", "name": "Starry sky"},
  {"id": 9, "group": "Scenes", "name": "Romantic"},
  {"id": 10, "group": "Scenes", "name": "Disco"},
  {"id": 11, "group": "Scenes", "name": "Rainbow"},
  {"id": 12, "group": "Scenes", "name": "Movie"},
  {"id": 13, "group": "Scenes", "name": "Christmas"},
  {"id": 14, "group": "Scenes", "name": "Flowing"},
  {"id": 15, "group": "Scenes", "name": "Sleeping"},
  {"id": 16, "group": "Scenes", "name": "Ocean"},
  {"id": 17, "group": "Scenes", "name": "Forest"},
  {"id": 18, "group": "Scenes", "name": "Reading"},
  {"id": 19, "group": "Scenes", "name": "Working"},
  {"id": 20, "group": "Scenes", "name": "Dazzle"},
  {"id": 21, "group": "Scenes", "name": "Gentle"},
  {"id": 22, "group": "Scenes", "name": "Wedding"},
  {"id": 23, "group": "Scenes", "name": "Snow"},
  {"id": 24, "group": "Scenes", "name": "Fire"},
  {"id": 25, "group": "Scenes", "name": "Lightning"},
  {"id": 26, "group": "Scenes", "name": "Valentine\\'s Day"},
  {"id": 27, "group": "Scenes", "name": "Hallowmas"},
  {"id": 28, "group": "Scenes", "name": "Warnning"},
]

export const elk: Effect[] = [
  {"id": 128, "name": "Static Red"},
  {"id": 129, "name": "Static Blue"},
  {"id": 130, "name": "Static Green"},
  {"id": 131, "name": "Static Cyan"},
  {"id": 132, "name": "Static Yellow"},
  {"id": 133, "name": "Static Purple"},
  {"id": 134, "name": "Static White"},
  {"id": 135, "name": "Three Color Jumping Change"},
  {"id": 136, "name": "Seven Color Jumping Change"},
  {"id": 137, "name": "Three Color Cross Fade"},
  {"id": 138, "name": "Seven Color Cross Fade"},
  {"id": 139, "name": "Red Gradual Change"},
  {"id": 140, "name": "Green Gradual Change"},
  {"id": 141, "name": "Blue Gradual Change"},
  {"id": 142, "name": "Yellow Gradual Change"},
  {"id": 143, "name": "Cyan Gradual Change"},
  {"id": 144, "name": "Purple Gradual Change"},
  {"id": 145, "name": "White Gradual Change"},
  {"id": 146, "name": "Red Green Cross Fade"},
  {"id": 147, "name": "Red Blue Cross Fade"},
  {"id": 148, "name": "Green Blue Cross Fade"},
  {"id": 149, "name": "Seven color Stobe Flash"},
  {"id": 150, "name": "Red Strobe Flash"},
  {"id": 151, "name": "Green Strobe Flash"},
  {"id": 152, "name": "Blue Strobe Flash"},
  {"id": 153, "name": "Yellow Strobe Flash"},
  {"id": 154, "name": "Cyan Strobe Flash"},
  {"id": 155, "name": "Purple Strobe Flash"},
  {"id": 156, "name": "White Strobe Flash"},
]

export const ledble: Effect[] = [
  {"id": 135, "name": "Tricolor jump"},
  {"id": 136, "name": "Seven-color jump"},
  {"id": 137, "name": "Tricolor gradient"},
  {"id": 138, "name": "even-color gradient"},
  {"id": 139, "name": "Red gradient"},
  {"id": 140, "name": "Green gradient"},
  {"id": 141, "name": "Blue gradient"},
  {"id": 142, "name": "Yellow gradient"},
  {"id": 143, "name": "Cyan gradient"},
  {"id": 144, "name": "Purple gradient"},
  {"id": 145, "name": "White gradient"},
  {"id": 146, "name": "Red-Green gradient"},
  {"id": 147, "name": "Red-Blue gradient"},
  {"id": 148, "name": "Green-Blue gradient"},
  {"id": 149, "name": "Seven-color flash"},
  {"id": 150, "name": "Red flash"},
  {"id": 151, "name": "Green flash"},
  {"id": 152, "name": "Blue flash"},
  {"id": 153, "name": "Yellow flash"},
  {"id": 154, "name": "Cyan flash"},
  {"id": 155, "name": "Purple flash"},
  {"id": 156, "name": "White flash"},
  {"id": 157, "name": "Seven-color breathe"},
]

export default { melk, elk, ledble }
