// GENERATED from docs/protocol/*.tsv by tools/gen-effects.py — do not edit by hand.
import type { Effect } from './types'

export const melk: Effect[] = [
  {"id": 0, "group": "Basic", "name": "Auto Play"},
  {"id": 1, "group": "Basic", "name": "Magic Forward"},
  {"id": 2, "group": "Basic", "name": "Magic Back"},
  {"id": 212, "group": "Basic", "name": "7-Color Energy"},
  {"id": 193, "group": "Basic", "name": "7-Color Jump"},
  {"id": 194, "group": "Basic", "name": "R-G-B Jump"},
  {"id": 195, "group": "Basic", "name": "Y-C-P Jump"},
  {"id": 196, "group": "Basic", "name": "7-Color Strobe"},
  {"id": 197, "group": "Basic", "name": "R-G-B Strobe"},
  {"id": 198, "group": "Basic", "name": "Y-C-P Strobe"},
  {"id": 199, "group": "Basic", "name": "7-Color Gradual"},
  {"id": 200, "group": "Basic", "name": "R-Y Gradual"},
  {"id": 201, "group": "Basic", "name": "R-P Gradual"},
  {"id": 202, "group": "Basic", "name": "G-C Gradual"},
  {"id": 203, "group": "Basic", "name": "G-Y Gradual"},
  {"id": 204, "group": "Basic", "name": "B-P Gradual"},
  {"id": 205, "group": "Basic", "name": "Red Marquee"},
  {"id": 206, "group": "Basic", "name": "Green Marquee"},
  {"id": 207, "group": "Basic", "name": "Blue Marquee"},
  {"id": 208, "group": "Basic", "name": "Yellow Marquee"},
  {"id": 209, "group": "Basic", "name": "Cyan Marquee"},
  {"id": 210, "group": "Basic", "name": "Purple Marquee"},
  {"id": 211, "group": "Basic", "name": "White Marquee"},
  {"id": 77, "group": "Basic", "name": "7-Color Race"},
  {"id": 78, "group": "Basic", "name": "7-Color Race Back"},
  {"id": 79, "group": "Basic", "name": "R-G-B Race"},
  {"id": 80, "group": "Basic", "name": "R-G-B Race Back"},
  {"id": 81, "group": "Basic", "name": "Y-C-P Race"},
  {"id": 82, "group": "Basic", "name": "Y-C-P Race Back"},
  {"id": 83, "group": "Basic", "name": "7-Color Wave"},
  {"id": 84, "group": "Basic", "name": "7-Color Wave Back"},
  {"id": 85, "group": "Basic", "name": "R-G-B Wave"},
  {"id": 86, "group": "Basic", "name": "R-G-B Wave Back"},
  {"id": 87, "group": "Basic", "name": "Y-C-P Wave"},
  {"id": 88, "group": "Basic", "name": "Y-C-P Wave Back"},
  {"id": 181, "group": "Basic", "name": "7-Color Flush"},
  {"id": 182, "group": "Basic", "name": "7-Color Flush Back"},
  {"id": 183, "group": "Basic", "name": "R-G-B Flush"},
  {"id": 184, "group": "Basic", "name": "R-G-B Flush Back"},
  {"id": 185, "group": "Basic", "name": "Y-C-P Flush"},
  {"id": 186, "group": "Basic", "name": "Y-C-P Flush Back"},
  {"id": 187, "group": "Basic", "name": "7-Color Flush Close"},
  {"id": 188, "group": "Basic", "name": "7-Color Flush Open"},
  {"id": 189, "group": "Basic", "name": "R-G-B Flush Close"},
  {"id": 190, "group": "Basic", "name": "R-G-B Flush Open"},
  {"id": 191, "group": "Basic", "name": "Y-C-P Flush Close"},
  {"id": 192, "group": "Basic", "name": "Y-C-P Flush Open"},
  {"id": 57, "group": "Curtain", "name": "7-Color Close"},
  {"id": 58, "group": "Curtain", "name": "7-Color Open"},
  {"id": 59, "group": "Curtain", "name": "R-G-B Close"},
  {"id": 60, "group": "Curtain", "name": "R-G-B Open"},
  {"id": 61, "group": "Curtain", "name": "Y-C-P Close"},
  {"id": 62, "group": "Curtain", "name": "Y-C-P Open"},
  {"id": 63, "group": "Curtain", "name": "Red Close"},
  {"id": 64, "group": "Curtain", "name": "Red Open"},
  {"id": 65, "group": "Curtain", "name": "Green Close"},
  {"id": 66, "group": "Curtain", "name": "Green Open"},
  {"id": 67, "group": "Curtain", "name": "Blue Close"},
  {"id": 68, "group": "Curtain", "name": "Blue Open"},
  {"id": 69, "group": "Curtain", "name": "Yellow Close"},
  {"id": 70, "group": "Curtain", "name": "Yellow Open"},
  {"id": 71, "group": "Curtain", "name": "Cyan Close"},
  {"id": 72, "group": "Curtain", "name": "Cyan Open"},
  {"id": 73, "group": "Curtain", "name": "Purple Close"},
  {"id": 74, "group": "Curtain", "name": "Purple Open"},
  {"id": 75, "group": "Curtain", "name": "White Close"},
  {"id": 76, "group": "Curtain", "name": "White Open"},
  {"id": 3, "group": "Trans", "name": "7-Color Trans"},
  {"id": 4, "group": "Trans", "name": "7-Color Trans Back"},
  {"id": 5, "group": "Trans", "name": "R-G-B Trans"},
  {"id": 6, "group": "Trans", "name": "R-G-B Trans Back"},
  {"id": 7, "group": "Trans", "name": "Y-C-P Trans"},
  {"id": 8, "group": "Trans", "name": "Y-C-P Trans Back"},
  {"id": 9, "group": "Trans", "name": "6-Color to Red"},
  {"id": 10, "group": "Trans", "name": "6-Color to Red Back"},
  {"id": 11, "group": "Trans", "name": "6-Color to Green"},
  {"id": 12, "group": "Trans", "name": "6-Color to Green Back"},
  {"id": 13, "group": "Trans", "name": "6-Color to Blue"},
  {"id": 14, "group": "Trans", "name": "6-Color to Blue Back"},
  {"id": 15, "group": "Trans", "name": "6-Color to Cyan"},
  {"id": 16, "group": "Trans", "name": "6-Color to Cyan Back"},
  {"id": 17, "group": "Trans", "name": "6-Color to Yellow"},
  {"id": 18, "group": "Trans", "name": "6-Color to Yellow Back"},
  {"id": 19, "group": "Trans", "name": "6-Color to Purple"},
  {"id": 20, "group": "Trans", "name": "6-Color to Purple Back"},
  {"id": 21, "group": "Trans", "name": "6-Color to White"},
  {"id": 22, "group": "Trans", "name": "6-Color to White Back"},
  {"id": 39, "group": "Water", "name": "7-Color Water"},
  {"id": 40, "group": "Water", "name": "7-Color Water Back"},
  {"id": 41, "group": "Water", "name": "R-G-B Water"},
  {"id": 42, "group": "Water", "name": "R-G-B Water Back"},
  {"id": 43, "group": "Water", "name": "Y-C-P Water"},
  {"id": 44, "group": "Water", "name": "Y-C-P Water Back"},
  {"id": 45, "group": "Water", "name": "R-G Water"},
  {"id": 46, "group": "Water", "name": "R-G Water Back"},
  {"id": 47, "group": "Water", "name": "G-B Water"},
  {"id": 48, "group": "Water", "name": "G-B Water Back"},
  {"id": 49, "group": "Water", "name": "Y-B Water"},
  {"id": 50, "group": "Water", "name": "Y-B Water Back"},
  {"id": 51, "group": "Water", "name": "Y-C Water"},
  {"id": 52, "group": "Water", "name": "Y-C Water Back"},
  {"id": 53, "group": "Water", "name": "C-P Water"},
  {"id": 54, "group": "Water", "name": "C-P Water Back"},
  {"id": 55, "group": "Water", "name": "White Water"},
  {"id": 56, "group": "Water", "name": "White Water Back"},
  {"id": 143, "group": "Flow", "name": "W-R-W Flow"},
  {"id": 144, "group": "Flow", "name": "W-R-W Flow Back"},
  {"id": 145, "group": "Flow", "name": "W-G-W Flow"},
  {"id": 146, "group": "Flow", "name": "W-G-W Flow Back"},
  {"id": 147, "group": "Flow", "name": "W-B-W Flow"},
  {"id": 148, "group": "Flow", "name": "W-B-W Flow Back"},
  {"id": 149, "group": "Flow", "name": "W-Y-W Flow"},
  {"id": 150, "group": "Flow", "name": "W-Y-W Flow Back"},
  {"id": 151, "group": "Flow", "name": "W-C-W Flow"},
  {"id": 152, "group": "Flow", "name": "W-C-W Flow Back"},
  {"id": 153, "group": "Flow", "name": "W-P-W Flow"},
  {"id": 154, "group": "Flow", "name": "W-P-W Flow Back"},
  {"id": 155, "group": "Flow", "name": "R-W-R Flow"},
  {"id": 156, "group": "Flow", "name": "R-W-R Flow Back"},
  {"id": 157, "group": "Flow", "name": "G-W-G Flow"},
  {"id": 158, "group": "Flow", "name": "G-W-G Flow Back"},
  {"id": 159, "group": "Flow", "name": "B-W-B Flow"},
  {"id": 160, "group": "Flow", "name": "B-W-B Flow Back"},
  {"id": 161, "group": "Flow", "name": "Y-W-Y Flow"},
  {"id": 162, "group": "Flow", "name": "Y-W-Y Flow Back"},
  {"id": 163, "group": "Flow", "name": "C-W-C Flow"},
  {"id": 164, "group": "Flow", "name": "C-W-C Flow Back"},
  {"id": 165, "group": "Flow", "name": "P-W-P Flow"},
  {"id": 166, "group": "Flow", "name": "P-W-P Flow Back"},
  {"id": 23, "group": "Tail", "name": "7-Color Tail"},
  {"id": 24, "group": "Tail", "name": "7-Color Tail Back"},
  {"id": 25, "group": "Tail", "name": "Red Tail"},
  {"id": 26, "group": "Tail", "name": "Red Tail Back"},
  {"id": 27, "group": "Tail", "name": "Green Tail"},
  {"id": 28, "group": "Tail", "name": "Green Tail Back"},
  {"id": 29, "group": "Tail", "name": "Blue Tail"},
  {"id": 30, "group": "Tail", "name": "Blue Tail Back"},
  {"id": 31, "group": "Tail", "name": "Yellow Tail"},
  {"id": 32, "group": "Tail", "name": "Yellow Tail Back"},
  {"id": 33, "group": "Tail", "name": "Cyan Tail"},
  {"id": 34, "group": "Tail", "name": "Cyan Tail Back"},
  {"id": 35, "group": "Tail", "name": "Purple Tail"},
  {"id": 36, "group": "Tail", "name": "Purple Tail Back"},
  {"id": 37, "group": "Tail", "name": "White Tail"},
  {"id": 38, "group": "Tail", "name": "White Tail Back"},
  {"id": 89, "group": "Run", "name": "Red Running"},
  {"id": 91, "group": "Run", "name": "Green Running"},
  {"id": 93, "group": "Run", "name": "Blue Running"},
  {"id": 95, "group": "Run", "name": "Yellow Running"},
  {"id": 97, "group": "Run", "name": "Cyan Running"},
  {"id": 99, "group": "Run", "name": "Purple Running"},
  {"id": 101, "group": "Run", "name": "White Running"},
  {"id": 103, "group": "Run", "name": "7-Color Running"},
  {"id": 105, "group": "Run", "name": "R-G-B Running"},
  {"id": 107, "group": "Run", "name": "Y-C-P Running"},
  {"id": 109, "group": "Run", "name": "B-P-C-Y Running"},
  {"id": 111, "group": "Run", "name": "B-G-C-Y Running"},
  {"id": 113, "group": "Run", "name": "Red-Dot in White Running"},
  {"id": 115, "group": "Run", "name": "Green-Dot in Red Running"},
  {"id": 117, "group": "Run", "name": "Blue-Dot in Green Running"},
  {"id": 119, "group": "Run", "name": "Yellow-Dot in Blue Running"},
  {"id": 121, "group": "Run", "name": "Cyan-Dot in Yellow Running"},
  {"id": 123, "group": "Run", "name": "Purple-Dot in Cyan Running"},
  {"id": 125, "group": "Run", "name": "White-Dot in Purple Running"},
  {"id": 127, "group": "Run", "name": "White-Dot in Red Running"},
  {"id": 129, "group": "Run", "name": "7-Color in Red Running"},
  {"id": 131, "group": "Run", "name": "7-Color in Green Running"},
  {"id": 133, "group": "Run", "name": "7-Color in Blue Running"},
  {"id": 135, "group": "Run", "name": "7-Color in Yellow Running"},
  {"id": 137, "group": "Run", "name": "7-Color in Cyan Running"},
  {"id": 139, "group": "Run", "name": "7-Color in Purple Running"},
  {"id": 141, "group": "Run", "name": "7-Color in White Running"},
  {"id": 167, "group": "Run", "name": "Green-Dot in Blue Running"},
  {"id": 169, "group": "Run", "name": "Green-Dot in Red Running"},
  {"id": 171, "group": "Run", "name": "Red-Dot in Blue Running"},
  {"id": 173, "group": "Run", "name": "Cyan-Dot in Yellow Running"},
  {"id": 175, "group": "Run", "name": "Yellow-Dot in Purple Running"},
  {"id": 177, "group": "Run", "name": "White-Dot in Yelllow Running"},
  {"id": 179, "group": "Run", "name": "Yellow-Dot in White Running"},
  {"id": 90, "group": "RunBack", "name": "Red Run Back"},
  {"id": 92, "group": "RunBack", "name": "Green Run Back"},
  {"id": 94, "group": "RunBack", "name": "Blue Run Back"},
  {"id": 96, "group": "RunBack", "name": "Yellow Run Back"},
  {"id": 98, "group": "RunBack", "name": "Cyan Run Back"},
  {"id": 100, "group": "RunBack", "name": "Purple Run Back"},
  {"id": 102, "group": "RunBack", "name": "White Run Back"},
  {"id": 104, "group": "RunBack", "name": "7-Color Run Back"},
  {"id": 106, "group": "RunBack", "name": "R-G-B Run Back"},
  {"id": 108, "group": "RunBack", "name": "Y-C-P Run Back"},
  {"id": 110, "group": "RunBack", "name": "B-P-C-Y Run Back"},
  {"id": 112, "group": "RunBack", "name": "B-G-C-Y Run Back"},
  {"id": 114, "group": "RunBack", "name": "Red-Dot in White Run Back"},
  {"id": 116, "group": "RunBack", "name": "Green-Dot in Red Run Back"},
  {"id": 118, "group": "RunBack", "name": "Blue-Dot in Green Run Back"},
  {"id": 120, "group": "RunBack", "name": "Yellow-Dot in Blue Run Back"},
  {"id": 122, "group": "RunBack", "name": "Cyan-Dot in Yellow Run Back"},
  {"id": 124, "group": "RunBack", "name": "Purple-Dot in Cyan Run Back"},
  {"id": 126, "group": "RunBack", "name": "White-Dot in Purple Run Back"},
  {"id": 128, "group": "RunBack", "name": "White-Dot in Red Run Back"},
  {"id": 130, "group": "RunBack", "name": "7-Color in Red Run Back"},
  {"id": 132, "group": "RunBack", "name": "7-Color in Green Run Back"},
  {"id": 134, "group": "RunBack", "name": "7-Color in Blue Run Back"},
  {"id": 136, "group": "RunBack", "name": "7-Color in Yellow Run Back"},
  {"id": 138, "group": "RunBack", "name": "7-Color in Cyan Run Back"},
  {"id": 140, "group": "RunBack", "name": "7-Color in Purple Run Back"},
  {"id": 142, "group": "RunBack", "name": "7-Color in White Run Back"},
  {"id": 168, "group": "RunBack", "name": "Green-Dot in Blue Run Back"},
  {"id": 170, "group": "RunBack", "name": "Green-Dot in Red Run Back"},
  {"id": 172, "group": "RunBack", "name": "Red-Dot in Blue Run Back"},
  {"id": 174, "group": "RunBack", "name": "Cyan-Dot in Yellow Run Back"},
  {"id": 176, "group": "RunBack", "name": "Yellow-Dot in Purple Run Back"},
  {"id": 178, "group": "RunBack", "name": "White-Dot in Yelllow Run Back"},
  {"id": 180, "group": "RunBack", "name": "Yellow-Dot in White Run Back"},
  {"id": 1, "group": "Scenes", "name": "Sunrise"},
  {"id": 2, "group": "Scenes", "name": "Sunset"},
  {"id": 3, "group": "Scenes", "name": "Birthday"},
  {"id": 4, "group": "Scenes", "name": "Candlelight"},
  {"id": 5, "group": "Scenes", "name": "Fireworks"},
  {"id": 6, "group": "Scenes", "name": "Party"},
  {"id": 7, "group": "Scenes", "name": "Datiny"},
  {"id": 8, "group": "Scenes", "name": "Starry sky"},
  {"id": 9, "group": "Scenes", "name": "Romantic"},
  {"id": 10, "group": "Scenes", "name": "Disco"},
  {"id": 11, "group": "Scenes", "name": "Rainbow"},
  {"id": 12, "group": "Scenes", "name": "Movie"},
  {"id": 13, "group": "Scenes", "name": "Christmas"},
  {"id": 14, "group": "Scenes", "name": "Flowing"},
  {"id": 15, "group": "Scenes", "name": "Sleeping"},
  {"id": 16, "group": "Scenes", "name": "Ocean"},
  {"id": 17, "group": "Scenes", "name": "Forest"},
  {"id": 18, "group": "Scenes", "name": "Reading"},
  {"id": 19, "group": "Scenes", "name": "Working"},
  {"id": 20, "group": "Scenes", "name": "Dazzle"},
  {"id": 21, "group": "Scenes", "name": "Gentle"},
  {"id": 22, "group": "Scenes", "name": "Wedding"},
  {"id": 23, "group": "Scenes", "name": "Snow"},
  {"id": 24, "group": "Scenes", "name": "Fire"},
  {"id": 25, "group": "Scenes", "name": "Lightning"},
  {"id": 26, "group": "Scenes", "name": "Valentine\\'s Day"},
  {"id": 27, "group": "Scenes", "name": "Hallowmas"},
  {"id": 28, "group": "Scenes", "name": "Warnning"},
]

export const elk: Effect[] = [
  {"id": 128, "name": "Static Red"},
  {"id": 129, "name": "Static Blue"},
  {"id": 130, "name": "Static Green"},
  {"id": 131, "name": "Static Cyan"},
  {"id": 132, "name": "Static Yellow"},
  {"id": 133, "name": "Static Purple"},
  {"id": 134, "name": "Static White"},
  {"id": 135, "name": "Three Color Jumping Change"},
  {"id": 136, "name": "Seven Color Jumping Change"},
  {"id": 137, "name": "Three Color Cross Fade"},
  {"id": 138, "name": "Seven Color Cross Fade"},
  {"id": 139, "name": "Red Gradual Change"},
  {"id": 140, "name": "Green Gradual Change"},
  {"id": 141, "name": "Blue Gradual Change"},
  {"id": 142, "name": "Yellow Gradual Change"},
  {"id": 143, "name": "Cyan Gradual Change"},
  {"id": 144, "name": "Purple Gradual Change"},
  {"id": 145, "name": "White Gradual Change"},
  {"id": 146, "name": "Red Green Cross Fade"},
  {"id": 147, "name": "Red Blue Cross Fade"},
  {"id": 148, "name": "Green Blue Cross Fade"},
  {"id": 149, "name": "Seven color Stobe Flash"},
  {"id": 150, "name": "Red Strobe Flash"},
  {"id": 151, "name": "Green Strobe Flash"},
  {"id": 152, "name": "Blue Strobe Flash"},
  {"id": 153, "name": "Yellow Strobe Flash"},
  {"id": 154, "name": "Cyan Strobe Flash"},
  {"id": 155, "name": "Purple Strobe Flash"},
  {"id": 156, "name": "White Strobe Flash"},
]

export const ledble: Effect[] = [
  {"id": 135, "name": "Tricolor jump"},
  {"id": 136, "name": "Seven-color jump"},
  {"id": 137, "name": "Tricolor gradient"},
  {"id": 138, "name": "even-color gradient"},
  {"id": 139, "name": "Red gradient"},
  {"id": 140, "name": "Green gradient"},
  {"id": 141, "name": "Blue gradient"},
  {"id": 142, "name": "Yellow gradient"},
  {"id": 143, "name": "Cyan gradient"},
  {"id": 144, "name": "Purple gradient"},
  {"id": 145, "name": "White gradient"},
  {"id": 146, "name": "Red-Green gradient"},
  {"id": 147, "name": "Red-Blue gradient"},
  {"id": 148, "name": "Green-Blue gradient"},
  {"id": 149, "name": "Seven-color flash"},
  {"id": 150, "name": "Red flash"},
  {"id": 151, "name": "Green flash"},
  {"id": 152, "name": "Blue flash"},
  {"id": 153, "name": "Yellow flash"},
  {"id": 154, "name": "Cyan flash"},
  {"id": 155, "name": "Purple flash"},
  {"id": 156, "name": "White flash"},
  {"id": 157, "name": "Seven-color breathe"},
]

export const ledcar: Effect[] = [
  {"id": 135, "name": "Tricolor jump"},
  {"id": 136, "name": "Seven-color jump"},
  {"id": 137, "name": "Tricolor gradient"},
  {"id": 138, "name": "Seven-color gradient"},
  {"id": 139, "name": "Red gradient"},
  {"id": 140, "name": "Green gradient"},
  {"id": 141, "name": "Blue gradient"},
  {"id": 142, "name": "Yellow gradient"},
  {"id": 143, "name": "Cyan gradient"},
  {"id": 144, "name": "Purple gradient"},
  {"id": 145, "name": "White gradient"},
  {"id": 146, "name": "Red-Green gradient"},
  {"id": 147, "name": "Red-Blue gradient"},
  {"id": 148, "name": "Green-Blue gradient"},
  {"id": 149, "name": "Seven-color flash"},
  {"id": 150, "name": "Red flash"},
  {"id": 151, "name": "Green flash"},
  {"id": 152, "name": "Blue flash"},
  {"id": 153, "name": "Yellow flash"},
  {"id": 154, "name": "Cyan flash"},
  {"id": 155, "name": "Purple flash"},
  {"id": 156, "name": "White flash"},
  {"id": 157, "name": "Seven Colored Breath"},
]

export const leddmx: Effect[] = [
  {"id": 255, "name": "AUTO"},
  {"id": 1, "name": "Forward Dreaming"},
  {"id": 2, "name": "Backward Dreaming"},
  {"id": 3, "name": "Forward 7 Colors"},
  {"id": 4, "name": "Backward 7 Colors"},
  {"id": 5, "name": "Forward RD/GN/BU"},
  {"id": 6, "name": "Backward RD/GN/BU"},
  {"id": 7, "name": "Forward YE/CN/VT"},
  {"id": 8, "name": "Backward YE/CN/VT"},
  {"id": 9, "name": "Forward 6 Colors RD"},
  {"id": 10, "name": "Backward 6 Colors RD"},
  {"id": 11, "name": "Forward 6 Colors GN"},
  {"id": 12, "name": "Backward 6 Colors GN"},
  {"id": 13, "name": "Forward 6 Colors BU"},
  {"id": 14, "name": "Backward 6 Colors BU"},
  {"id": 15, "name": "Forward 6 Colors CN"},
  {"id": 16, "name": "Backward 6 Colors CN"},
  {"id": 17, "name": "Forward 6 Colors YE"},
  {"id": 18, "name": "Backward 6 Colors YE"},
  {"id": 19, "name": "Forward 6 Colors VT"},
  {"id": 20, "name": "Backward 6 Colors VT"},
  {"id": 21, "name": "Forward 6 Colors WH"},
  {"id": 22, "name": "Backward 6 Colors WH"},
  {"id": 23, "name": "Forward Trailing 7 Colors"},
  {"id": 24, "name": "Backward Trailing 7 Colors"},
  {"id": 25, "name": "Forward Trailing RD"},
  {"id": 26, "name": "Backward Trailing RD"},
  {"id": 27, "name": "Forward Trailing GN"},
  {"id": 28, "name": "Backward Trailing GN"},
  {"id": 29, "name": "Forward Trailing BU"},
  {"id": 30, "name": "Backward Trailing BU"},
  {"id": 31, "name": "Forward Trailing YE"},
  {"id": 32, "name": "Backward Trailing YE"},
  {"id": 33, "name": "Forward Trailing CN"},
  {"id": 34, "name": "Backward Trailing CN"},
  {"id": 35, "name": "Forward Trailing VT"},
  {"id": 36, "name": "Backward Trailing VT"},
  {"id": 37, "name": "Forward Trailing WH"},
  {"id": 38, "name": "Backward Trailing WH"},
  {"id": 39, "name": "Forward Streaming 7 Colors"},
  {"id": 40, "name": "Backward Streaming 7 Colors"},
  {"id": 41, "name": "Forward Streaming RD/GN/BU"},
  {"id": 42, "name": "Backward Streaming RD/GN/BU"},
  {"id": 43, "name": "Forward Streaming YE/CN/VT"},
  {"id": 44, "name": "Backward Streaming YE/CN/VT"},
  {"id": 45, "name": "Forward Streaming RD/GN"},
  {"id": 46, "name": "Backward Streaming RD/GN"},
  {"id": 47, "name": "Forward Streaming GN/BU"},
  {"id": 48, "name": "Backward Streaming GN/BU"},
  {"id": 49, "name": "Forward Streaming YE/BU"},
  {"id": 50, "name": "Backward Streaming YE/BU"},
  {"id": 51, "name": "Forward Streaming YE/CN"},
  {"id": 52, "name": "Backward Streaming YE/CN"},
  {"id": 53, "name": "Forward Streaming CN/VT"},
  {"id": 54, "name": "Backward Streaming CN/VT"},
  {"id": 55, "name": "Forward Streaming BK/WH"},
  {"id": 56, "name": "Backward Streaming BK/WH"},
  {"id": 57, "name": "Open Curtain 7 Colors"},
  {"id": 58, "name": "Close Curtain 7 Colors"},
  {"id": 59, "name": "Open Curtain RD/GN/BU"},
  {"id": 60, "name": "Close Curtain RD/GN/BU"},
  {"id": 61, "name": "Open Curtain YE/CN/VT"},
  {"id": 62, "name": "Close Curtain YE/CN/VT"},
  {"id": 63, "name": "Forward Follow Spot 7 Colors"},
  {"id": 64, "name": "Backward Follow Spot 7 Colors"},
  {"id": 65, "name": "Forward Follow Spot RD/GN/BU"},
  {"id": 66, "name": "Backward Follow Spot RD/GN/BU"},
  {"id": 67, "name": "Forward Follow Spot YE/CN/VT"},
  {"id": 68, "name": "Backward Follow Spot YE/CN/VT"},
  {"id": 69, "name": "Forward Flutter 7 Colors"},
  {"id": 70, "name": "Backward Flutter 7 Colors"},
  {"id": 71, "name": "Forward Flutter RD/GN/BU"},
  {"id": 72, "name": "Backward Flutter RD/GN/BU"},
  {"id": 73, "name": "Forward Flutter YE/CN/VT"},
  {"id": 74, "name": "Backward Flutter YE/CN/VT"},
  {"id": 75, "name": "Hop 7 Colors"},
  {"id": 76, "name": "Hop RD/GN/BU"},
  {"id": 77, "name": "Hop RD/GN/BU"},
  {"id": 78, "name": "Strobe 7 Colors"},
  {"id": 79, "name": "Strobe RD/GN/BU"},
  {"id": 80, "name": "Strobe YE/CN/VT"},
  {"id": 81, "name": "Gradual 7 Colors"},
  {"id": 82, "name": "Gradual RD/E"},
  {"id": 83, "name": "Gradual RD/VT"},
  {"id": 84, "name": "Gradual GN/CN"},
  {"id": 85, "name": "Gradual GN/YE"},
  {"id": 86, "name": "Gradual BU/VT"},
  {"id": 87, "name": "Close Curtain RD"},
  {"id": 88, "name": "Close Curtain GN"},
  {"id": 89, "name": "Close Curtain BU"},
  {"id": 90, "name": "Close Curtain YE"},
  {"id": 91, "name": "Close Curtain CN"},
  {"id": 92, "name": "Close Curtain VT"},
  {"id": 93, "name": "Close Curtain WH"},
  {"id": 94, "name": "Open Curtain RD"},
  {"id": 95, "name": "Open Curtain GN"},
  {"id": 96, "name": "Open Curtain BU"},
  {"id": 97, "name": "Open Curtain YE"},
  {"id": 98, "name": "Open Curtain CN"},
  {"id": 99, "name": "Open Curtain VT"},
  {"id": 100, "name": "Open Curtain WH"},
  {"id": 101, "name": "Horse Race RD"},
  {"id": 102, "name": "Horse Race GN"},
  {"id": 103, "name": "Horse Race BU"},
  {"id": 104, "name": "Horse Race YE"},
  {"id": 105, "name": "Horse Race CN"},
  {"id": 106, "name": "Horse Race VT"},
  {"id": 107, "name": "Horse Race WH"},
  {"id": 108, "name": "Forward Run RD"},
  {"id": 109, "name": "Backward Run RD"},
  {"id": 110, "name": "Forward Run GN"},
  {"id": 111, "name": "Backward Run GN"},
  {"id": 112, "name": "Forward Run BU"},
  {"id": 113, "name": "Backward Run BU"},
  {"id": 114, "name": "Forward Run YE"},
  {"id": 115, "name": "Backward Run YE"},
  {"id": 116, "name": "Forward Run CN"},
  {"id": 117, "name": "Backward Run CN"},
  {"id": 118, "name": "Forward Run VT"},
  {"id": 119, "name": "Backward Run VT"},
  {"id": 120, "name": "Forward Run WH"},
  {"id": 121, "name": "Backward Run WH"},
  {"id": 122, "name": "Forward Run 7 Colors"},
  {"id": 123, "name": "Backward Run 7 Colors"},
  {"id": 124, "name": "Forward Run RD/GN/BU"},
  {"id": 125, "name": "Backward Run RD/GN/BU"},
  {"id": 126, "name": "Forward Run YE/CN/VT"},
  {"id": 127, "name": "Backward Run YE/CN/VT"},
  {"id": 128, "name": "Forward Run BU/YE/VT"},
  {"id": 129, "name": "Forward Run GN/BU/YE"},
  {"id": 130, "name": "Backward Run BU/YE/VT"},
  {"id": 131, "name": "Forward Run RD/ON/WH"},
  {"id": 132, "name": "Backward Run RD/ON/WH"},
  {"id": 133, "name": "Forward Run GN ON RD"},
  {"id": 134, "name": "Backward Run GN ON RD"},
  {"id": 135, "name": "Forward Run BU ON GN"},
  {"id": 136, "name": "Backward Run BU ON GN"},
  {"id": 137, "name": "Forward Run YE ON BU"},
  {"id": 138, "name": "Backward Run YE ON BU"},
  {"id": 139, "name": "Forward Run CN ON YE"},
  {"id": 140, "name": "Backward Run CN ON YE"},
  {"id": 141, "name": "Forward Run VT ON CN"},
  {"id": 142, "name": "Backward Run VT ON CN"},
  {"id": 143, "name": "Forward Run WH ON VT"},
  {"id": 144, "name": "Backward Run WH ON VT"},
  {"id": 145, "name": "Forward Run WH ON RD"},
  {"id": 146, "name": "Backward Run WH ON RD"},
  {"id": 147, "name": "Forward Run 7 COLOR ON RD"},
  {"id": 148, "name": "Backward Run 7 COLOR ON RD"},
  {"id": 149, "name": "Forward Run 7 COLOR ON GN"},
  {"id": 150, "name": "Backward Run 7 COLOR ON GN"},
  {"id": 151, "name": "Forward Run 7 COLOR ON BU"},
  {"id": 152, "name": "Backward Run 7 COLOR ON BU"},
  {"id": 153, "name": "Forward Run 7 COLOR ON YE"},
  {"id": 154, "name": "Backward Run 7 COLOR ON YE"},
  {"id": 155, "name": "Forward Run 7 COLOR ON CN"},
  {"id": 156, "name": "Backward Run 7 COLOR ON CN"},
  {"id": 157, "name": "Forward Run 7 COLOR ON VT"},
  {"id": 158, "name": "Backward Run 7 COLOR ON VT"},
  {"id": 159, "name": "Forward Run 7 COLOR ON WH"},
  {"id": 160, "name": "Backward Run 7 COLOR ON WH"},
  {"id": 161, "name": "Forward Flow WH RD WH"},
  {"id": 162, "name": "Backward Flow WH RD WH"},
  {"id": 163, "name": "Forward Flow WH GN WH"},
  {"id": 164, "name": "Backward Flow WH GN WH"},
  {"id": 165, "name": "Forward Flow WH BU WH"},
  {"id": 166, "name": "Backward Flow WH BU WH"},
  {"id": 167, "name": "Forward Flow WH YE WH"},
  {"id": 168, "name": "Backward Flow WH YE WH"},
  {"id": 169, "name": "Forward Flow WH CN WH"},
  {"id": 170, "name": "Backward Flow WH CN WH"},
  {"id": 171, "name": "Forward Flow WH VT WH"},
  {"id": 172, "name": "Backward Flow WH VT WH"},
  {"id": 173, "name": "Forward Flow RD WH RD"},
  {"id": 174, "name": "Backward Flow RD WH RD"},
  {"id": 175, "name": "Forward Flow GN WH GN"},
  {"id": 176, "name": "Backward Flow GN WH GN"},
  {"id": 177, "name": "Forward Flow BU WH BU"},
  {"id": 178, "name": "Backward Flow BU WH BU"},
  {"id": 179, "name": "Forward Flow YE WH YE"},
  {"id": 180, "name": "Backward Flow YE WH YE"},
  {"id": 181, "name": "Forward Flow CN WH CN"},
  {"id": 182, "name": "Backward Flow CN WH CN"},
  {"id": 183, "name": "Forward Flow VT WH VT"},
  {"id": 184, "name": "Backward Flow VT WH VT"},
  {"id": 185, "name": "Forward Run GN ON BU"},
  {"id": 186, "name": "Backward Run GN ON BU"},
  {"id": 187, "name": "Forward Run GN ON RD"},
  {"id": 188, "name": "Backward Run GN ON RD"},
  {"id": 189, "name": "Forward Run RD ON BU"},
  {"id": 190, "name": "Backward Run RD ON BU"},
  {"id": 191, "name": "Forward Run CN ON YE"},
  {"id": 192, "name": "Backward Run CN ON YE"},
  {"id": 193, "name": "Forward Run YE ON VT"},
  {"id": 194, "name": "Backward Run YE ON VT"},
  {"id": 195, "name": "Forward Run WH ON YE"},
  {"id": 196, "name": "Backward Run WH ON YE"},
  {"id": 197, "name": "Forward Run YE ON WH"},
  {"id": 198, "name": "Backward Run YE ON WH"},
  {"id": 199, "name": "Forward Swab 7 COLORS"},
  {"id": 200, "name": "Backward Swab 7 COLORS"},
  {"id": 201, "name": "Forward Swab RD GN BU"},
  {"id": 202, "name": "Backward Swab RD GN BU"},
  {"id": 203, "name": "Forward Swab YE CN VT"},
  {"id": 204, "name": "Backward Swab YE CN VT"},
  {"id": 205, "name": "Open Curtain Swab 7 COLORS"},
  {"id": 206, "name": "Close Curtain Swab 7 COLORS"},
  {"id": 207, "name": "Open Curtain Swab R G B"},
  {"id": 208, "name": "Close Curtain Swab R G B"},
  {"id": 209, "name": "Open Curtain Swab Y C P"},
  {"id": 210, "name": "Close Curtain Swab Y C P"},
]

export const ledlike: Effect[] = [
  {"id": 0, "name": "Turn off"},
  {"id": 1, "name": "Turn on"},
  {"id": 2, "name": "All bright"},
  {"id": 3, "name": "Half bright"},
  {"id": 4, "name": "Slightly bright"},
  {"id": 5, "name": "breathing"},
  {"id": 6, "name": "Strobe"},
  {"id": 7, "name": "Flashing"},
]

export const ledpho: Effect[] = [
  {"id": 0, "name": "None"},
  {"id": 1, "name": "Alarm"},
  {"id": 2, "name": "Lightning"},
  {"id": 3, "name": "Flash"},
  {"id": 4, "name": "Flame"},
  {"id": 5, "name": "Explode"},
  {"id": 6, "name": "Candlelight"},
  {"id": 7, "name": "Get Together"},
  {"id": 8, "name": "Flicker"},
  {"id": 9, "name": "Starlight"},
  {"id": 10, "name": "Fireworks"},
  {"id": 11, "name": "Short Circuit"},
  {"id": 12, "name": "Pulse"},
  {"id": 13, "name": "Music"},
  {"id": 14, "name": "Rainbow"},
  {"id": 15, "name": "Breathe"},
]

export default { melk, elk, ledble, ledcar, leddmx, ledlike, ledpho }
